FROM node:18-alpine

RUN apk add --no-cache openssl git

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npx", "ts-node-dev", "-r", "tsconfig-paths/register", "--respawn", "--transpile-only", "src/main.ts"]
